### ISSUE TITLE
LICHEM Installation

### ISSUE THREAD

**Issue by Mawuli24** [CisnerosResearch/LICHEM#14]
Hi,

I tried installing LICHEM package and encountered the errors below and would appreciate your assistance. 

###################################################
#                                                 #
#   LICHEM: Layered Interacting CHEmical Models   #
#                                                 #
#        Symbiotic Computational Chemistry        #
#                                                 #
###################################################

### Compiling the LICHEM binary ###
g++ ./src/LICHEM.cpp -o /projects/welbornlab/softwares/LICHEM/bin/lichem -static -O3 -fopenmp -I./Eigen3/ -I./src/ -I./include/
In file included from ./include/LICHEM_headers.h:22,
                 from ./src/LICHEM.cpp:22:
./include/LICHEM_clibs.h:24:38: note: ‘#pragma message: OpenMP is enabled.’
   24 |  #pragma message("OpenMP is enabled.")
      |                                      ^
./include/LICHEM_clibs.h:34:40: note: ‘#pragma message: OpenACC is disabled.’
   34 |  #pragma message("OpenACC is disabled.")
      |                                        ^
In file included from ./Eigen3/Eigen/Core:379,
                 from ./include/LICHEM_matrix.h:22,
                 from ./include/LICHEM_headers.h:26:
./Eigen3/Eigen/src/Core/functors/StlFunctors.h:87:28: warning: ‘template<class _Predicate> class std::unary_negate’ is deprecated [-                         Wdeprecated-declarations]
   87 | struct functor_traits<std::unary_negate<T> >
      |                            ^~~~~~~~~~~~
In file included from /apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/string:49,
                 from /apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/bits/locale_classes.h:40,
                 from /apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/bits/ios_base.h:41,
                 from /apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/ios:44,
                 from /apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/ostream:40,
                 from /apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/iostream:41,
                 from ./include/LICHEM_clibs.h:40:
/apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/bits/stl_function.h:1024:33: note: declared here
 1024 |     class _GLIBCXX17_DEPRECATED unary_negate
      |                                 ^~~~~~~~~~~~
./Eigen3/Eigen/src/Core/functors/StlFunctors.h:91:28: warning: ‘template<class _Predicate> class std::binary_negate’ is deprecated [                         -Wdeprecated-declarations]
   91 | struct functor_traits<std::binary_negate<T> >
      |                            ^~~~~~~~~~~~~
/apps/easybuild/software/tinkercliffs-rome/GCCcore/13.2.0/include/c++/13.2.0/bits/stl_function.h:1051:33: note: declared here
 1051 |     class _GLIBCXX17_DEPRECATED binary_negate
      |                                 ^~~~~~~~~~~~~
In file included from ./include/LICHEM_QSM.h:123,
                 from ./include/LICHEM_headers.h:250:
./src/Optimization_tools.cpp: In function ‘double CalcForces(std::vector<QMMMAtom>&, QMMMSettings&, Eigen::VectorXd&, Eigen::VectorX                         d&, Eigen::VectorXd&, Eigen::VectorXd&, int, int, bool, std::fstream&)’:
./src/Optimization_tools.cpp:186:1: warning: no return statement in function returning non-void [-Wreturn-type]
  186 | }
      | ^
./src/Optimization_tools.cpp: In function ‘double CalcEnergy(std::vector<QMMMAtom>&, QMMMSettings&, Eigen::VectorXd&, Eigen::VectorX                         d&, Eigen::VectorXd&, std::fstream&)’:
./src/Optimization_tools.cpp:309:1: warning: no return statement in function returning non-void [-Wreturn-type]
  309 | }
      | ^
./src/Optimization_tools.cpp: In function ‘double runMMopt(std::vector<QMMMAtom>&, QMMMSettings&, std::fstream&)’:
./src/Optimization_tools.cpp:362:20: warning: control reaches end of non-void function [-Wreturn-type]
  362 |         logFile << '\n';
      |                    ^~~~
./src/Optimization_tools.cpp: In function ‘double runRestrMMopt(std::vector<QMMMAtom>&, QMMMSettings&, double, std::fstream&)’:
./src/Optimization_tools.cpp:403:52: warning: control reaches end of non-void function [-Wreturn-type]
  403 |     logFile << "Starting new QSM iteration. \n" << endl;
      |                                                    ^~~~
/apps/easybuild/software/tinkercliffs-rome/binutils/2.40-GCCcore-13.2.0/bin/ld: cannot find -lm: No such file or directory
/apps/easybuild/software/tinkercliffs-rome/binutils/2.40-GCCcore-13.2.0/bin/ld: cannot find -lpthread: No such file or directory
/apps/easybuild/software/tinkercliffs-rome/binutils/2.40-GCCcore-13.2.0/bin/ld: cannot find -lc: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [binary] Error 1

**Comment by g-andres** [comment]
please try compiling with gcc = 12.3.0 and mpich = 3.4.3
